// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHvVnegIpl33_TgAXMYGx6CDsc6SgBcYE',
    appId: '1:252659969164:web:4deb4e99d49e4c649e5fa9',
    messagingSenderId: '252659969164',
    projectId: 'tubes-test',
    authDomain: 'tubes-test.firebaseapp.com',
    storageBucket: 'tubes-test.firebasestorage.app',
    measurementId: 'G-LWWL719HKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlMPHA-XWDMBSoHU-au8XLVgNWphaJug',
    appId: '1:252659969164:android:e55302689669bfd29e5fa9',
    messagingSenderId: '252659969164',
    projectId: 'tubes-test',
    storageBucket: 'tubes-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPtJIM7GyJFh6nM9aQTpnRJdBDkvNiBM',
    appId: '1:252659969164:ios:a17fef9d1923dcf79e5fa9',
    messagingSenderId: '252659969164',
    projectId: 'tubes-test',
    storageBucket: 'tubes-test.firebasestorage.app',
    iosBundleId: 'com.example.tubesApb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArPtJIM7GyJFh6nM9aQTpnRJdBDkvNiBM',
    appId: '1:252659969164:ios:a17fef9d1923dcf79e5fa9',
    messagingSenderId: '252659969164',
    projectId: 'tubes-test',
    storageBucket: 'tubes-test.firebasestorage.app',
    iosBundleId: 'com.example.tubesApb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHvVnegIpl33_TgAXMYGx6CDsc6SgBcYE',
    appId: '1:252659969164:web:36c577102ac6eb689e5fa9',
    messagingSenderId: '252659969164',
    projectId: 'tubes-test',
    authDomain: 'tubes-test.firebaseapp.com',
    storageBucket: 'tubes-test.firebasestorage.app',
    measurementId: 'G-NVTS1V4SF7',
  );

}